import falloutLogo from '../assets/img/falloutLogo.png';
import fi1 from '../assets/img/fi1.jpg';
import fi2 from '../assets/img/fi2.jpg';
import fi3 from '../assets/img/fi3.jpg';
import fwp2 from '../assets/img/fwp2.jpg';
import fwp3 from '../assets/img/fwp3.jpg';
import fwp4 from '../assets/img/fwp4.jpg';
import fwp5 from '../assets/img/fwp5.jpg';
import fwp6 from '../assets/img/fwp6.jpg';
import fwp7 from '../assets/img/fwp7.jpg';
import fwpp from '../assets/img/fwpp.jpg';
import fwppi from '../assets/img/fwppi.jpg';
import f1i1 from '../assets/img/paraGaleria/fallout1/f1i1.jpg';
import f1i2 from '../assets/img/paraGaleria/fallout1/f1i2.jpg';
import f1i3 from '../assets/img/paraGaleria/fallout1/f1i3.jpg';
import f2i1 from '../assets/img/paraGaleria/fallout2/f2i1.jpg';
import f2i2 from '../assets/img/paraGaleria/fallout2/f2i2.jpg';
import f2i3 from '../assets/img/paraGaleria/fallout2/f2i3.jpg';
import f3i1 from '../assets/img/paraGaleria/fallout3/f3i1.jpg';
import f3i2 from '../assets/img/paraGaleria/fallout3/f3i2.jpg';

export { falloutLogo, fi1, fi2, fi3, fwp2, fwp3, fwp4, fwp5, fwp6, fwp7, fwpp, fwppi, f1i1, f1i2, f1i3, f2i1, f2i2, f2i3, f3i1, f3i2 };
