export const GET_OPTIONS = 'GET_OPTIONS';
export const GET_OPTIONS_LOADING = 'GET_OPTIONS_LOADING';
export const GET_OPTIONS_ERROR = 'GET_OPTIONS_ERROR';
export const HANDLE_OPTIONS_DROPDOWN = 'HANDLE_OPTIONS_DROPDOWN';
