export const HANDLE_FORM_SUBMIT = 'HANDLE_FORM_SUBMIT';
export const HANDLE_FORM_DATA = 'HANDLE_FORM_DATA';
export const HANDLE_FORM_LOADING = 'HANDLE_FORM_LOADING';
export const HANDLE_FORM_ERROR = 'HANDLE_FORM_ERROR';
